# Generated by Django 2.1.5 on 2019-02-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=400)),
                ('last_name', models.CharField(max_length=400)),
                ('address', models.CharField(max_length=600)),
                ('city', models.CharField(max_length=400)),
                ('payment_method', models.CharField(max_length=400)),
                ('payment_data', models.CharField(max_length=400)),
                ('items', models.TextField()),
                ('fullfilled', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=850)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('imgling', models.CharField(max_length=850)),
            ],
        ),
    ]
